sudo: false

language: node_js
node_js:
  - "10"
services: mongodb
cache:
  yarn: true
  directories:
    - "node_modules"
after_success:
  - echo "passed the test now building"
  # - yarn build
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_DEPLOY_KEY
  app: project-3-group
  on:
    repo: Siddant/project-03
