sudo: false

language: node_js
node_js:
  - "10.15.1"
services: mongodb
before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.14.0
cache:
  yarn: true
  directories:
    - "node_modules"
after_success:
  - echo "passed the test now building"
  # - yarn build
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_DEPLOY_KEY
  app: project-3-group
  on:
    repo: Siddant/project-03
