sudo: false

language: node_js
node_js:
  - "12"
services: mongodb
cache:
  yarn: true
  directories:
    - "node_modules"
# before_script:
#   - curl -o- -L https://yarnpkg.com/install.sh | bash -s
#   - export PATH=$HOME/.yarn/bin:$PATH
#   - yarn install

# script:
#   - yarn test
